### ISSUE TITLE
R16. Location field per default on proposal wizard

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a user, I would like to see the location field in the default setting and if my request does not have a location, check the "Has no location" checkbox. 

**Additional context**

**Mock up**
![Image](https://user-images.githubusercontent.com/40388743/186649675-c30d12c3-1e5d-49a2-9019-e49df04b286d.png)

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [x] As a user, I would like to see the location field in the default setting and if my request does not have a location, check the "Has no location" checkbox.

**Technical specification**
https://github.com/openpoke/decidim-module-reporting-proposals/issues/4

**Implementation**

- [x] https://github.com/openpoke/decidim-module-reporting-proposals/pull/9

**Testing**

**Comment by Naadjjaa** [comment]
@paarals Perfect, a small thing: After entering an adress, if i decide i don't want to send an adress, the "has no address" does not work properly:


![Image](https://user-images.githubusercontent.com/75797851/194286271-472ddd47-dd97-4a3f-b7f9-c9efc83b7ae9.png)

**Comment by paarals** [comment]
good catch @Naadjjaa !

**Comment by paarals** [comment]
working
