### ISSUE TITLE
R29. Compare proposals based on location coordinates proximity

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Compare proposals based on location coordinates proximity

**Mock up**

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [x] As a user in "compare step", I can see near location proposals 
- [x] Radius 30 meter
- [x] Accepted proposals also be compared
- [x] Compare proposals no older than 2 months

**Technical specifications**
https://github.com/openpoke/decidim-module-reporting-proposals/issues/6

**Implementation**

**Testing**

**Additional context**
It's a feature detected by Pokecode in order to improve performance.

**Comment by Naadjjaa** [comment]
@paarals Did you think about the user interaction in case the proposal is actually the same?

**Comment by paarals** [comment]
hi @Naadjjaa, you mean what if my proposal is the same as another user, what should I do?
The current logic of Decidim is that if the user sees an equal proposal in the comparison step, they should "discard" it

**Comment by Naadjjaa** [comment]
@paarals 

Keep the logic!

Compare all proposals only based on geolocation (and no longer on similar text). Radius 30 meter.
Will accepted proposals also be compared? If no, it should!
Can we please only compare proposals no older than 2 months?

**Comment by paarals** [comment]
closed by testing
