### ISSUE TITLE
R04. Improve the email notification for proposal valuators

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When a valuator is selected to comment on a proposal in the backend system, the valuator receives an email notification including a link to the proposal in the backend system.

As a valuer, I would like to receive an email with a link directly to the individual proposal as i am assigne (nothing is currently sent in this case). Same as #12

**Mock up**

**Does this issue could impact on users private data?**
No

**Acceptance criteria**
- [x] Improve the email notification for proposal valuators

**Technical specifications**
https://github.com/openpoke/decidim/issues/18

**Implementation**
- [x] Initial solution: https://github.com/openpoke/decidim/pull/23
- [x] Final solution: https://github.com/openpoke/decidim/pull/25

**Testing**
Steps to reproduce: https://letterbox.dev.pokecode.net/admin/participatory_processes/digital-letterbox/components/2/manage/
1. As a process-admin, I make new valuators in Process Admins
![Image](https://user-images.githubusercontent.com/40388743/193053118-46a24aeb-5b4f-4ebf-8cad-1f6995fac3dc.png)

2. As a process-admin, I assign a valuator in one or more proposal
![Image](https://user-images.githubusercontent.com/40388743/193053329-f288d387-bf64-4361-bada-123e6fc435be.png)

3. As a valuator, I received an email with assigned proposals to evaluate 
![Image](https://user-images.githubusercontent.com/40388743/193053526-92987f07-8ed2-41e9-844c-9b4ac239c975.png)

**Additional context**
Metadecidim proposal: https://meta.decidim.org/processes/roadmap/f/122/proposals/17113

**Comment by Naadjjaa** [comment]
@paarals Works, thank. Also the link is at the moment to the frontend not to the backend. We actually like that better!
