### ISSUE TITLE
R08. Hide proposals without publish

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a process-admin, I would like to be able to hide proposals directly via the backend without the need of first report the proposal via frontend.

**Mock up**

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [x] Hide proposals directly via backend

**Technical specifications**
https://github.com/openpoke/decidim-module-reporting-proposals/issues/2

**Implementation**

- [x] https://github.com/openpoke/decidim-module-reporting-proposals/pull/8

**Testing**
Steps to reproduce: https://letterbox.dev.pokecode.net/admin/participatory_processes/digital-letterbox/components/2/manage/
1. As an admin, I go to Proposal Dashboard 
2. I flag a proposal directly as an admin 
3. Flag proposal can be hidden 

Demo: https://user-images.githubusercontent.com/40388743/193052248-f38166d6-1a17-4c1e-8b9d-3bb02f3f96d9.mp4

**Additional context**

**Comment by Naadjjaa** [comment]
@paarals 
- After deleting / hiding. Are we still able to see the proposal?
- Are we still able to answer a proposal after deleting/ hiding?
- Are we able to answer before deleting?

**Comment by paarals** [comment]
The operation of this functionality is the same as "moderation".
-You will always see the proposal in the space of "moderations" of the process and "global moderations", when its reported.
-A moderate and hidden proposal, it can be shown again.
-To answer the proposal, it must be public (not hidden). If you hide it, this proposal goes to the moderation area. Therefore, the functionality to answer it is lost.

**Comment by paarals** [comment]
closed by sprint 3
