### ISSUE TITLE
R06. Overdue proposals highlighted in color

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a process-admin, I would like to see overdue proposals highlighted in color. The deadline could be defined per default or if possible individually.

**Mock up**
![Image](https://user-images.githubusercontent.com/40388743/189849416-948511c7-3fb8-40fa-85e7-7cb6c1f944dd.png)

**Does this issue could impact on users private data?**
No, it's about performance.

**Acceptance criteria**
- [ ] Show overdue proposals highlighted in color

**Technical specifications**
https://github.com/openpoke/decidim/issues/8
https://github.com/openpoke/decidim-module-reporting-proposals/issues/1

**Implementation**
- [x] Initial solution: https://github.com/openpoke/decidim/pull/9
- [x] Move solution to module: https://github.com/openpoke/decidim-module-reporting-proposals/pull/7

**Testing**
Not yet

**Additional context**
Original Decidim: 
![Image](https://user-images.githubusercontent.com/40388743/182794663-d590a07a-de4a-42b1-ab18-0ecf1dd4edc5.png)

**Comment by paarals** [comment]
Hi @Naadjjaa and @SandrineGis, there you have our mockup. 
Feel free for any feedback :)

**Comment by SandrineGis** [comment]
@paarals @Naadjjaa it looks good, but I don`t think I can test it or can I? I just see a printscreen. It would be enough to measure the overdue proposals in days instead of hours. Hours isn`t realistic. Are the completed proposals marked green?

**Comment by Naadjjaa** [comment]
Internal process to be defined. Idea: Urgency levels possible?

**Comment by microstudi** [comment]
This is testable at https://letterbox.dev.pokecode.net.
![image](https://user-images.githubusercontent.com/1401520/194292683-bb84e5cc-445f-4799-a795-383acddba03f.png)

Time to overdue is configurable in the component settings:
![image](https://user-images.githubusercontent.com/1401520/194292883-3c3f324e-9c8d-43bd-a493-505a3d88c5d6.png)

There's two types of overdue: 
1. Time while no answer has been given at all
2. Time from when it is in state "evaluating" to either accepted or rejected

**Comment by paarals** [comment]
closed by sprint 3
