### ISSUE TITLE
R38. Multiple pictures in the frontend reporting wizard

### ISSUE THREAD

**Issue by paarals** [stadtluzern/decidim-letterbox-damagereporting#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
multiple pictures in the frontend

**Mock up**

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [ ] As a user, I can upload more that 1 picture

**Technical specifications**

**Implementation**

**Testing**

**Additional context**

**Comment by Naadjjaa** [comment]
@paarals We will use general attachments instead. Therefore I close this issue.
