### ISSUE TITLE
Bug - uploading pdf to proposal

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-letterbox-damagereporting#56]
Other cities using our code-base noted that it is no longer possible to upload pdf documents to the proposal component. We should not interfere with other modules! What can we do regarding the fact that at the moment we have no more budget to implement the module a second time at the moment? @paarals 

Edit: in damage reporting module we have this box that is missing in the proposal?
![image](https://github.com/stadtluzern/decidim-letterbox-damagereporting/assets/75797851/5fc46046-c35e-4455-8198-a414a797b51b)

**Comment by microstudi** [comment]
We look at this and fix it @Naadjjaa no worries. It is strange because it shoudn't limit any uploads.
When you say it is not possible to upload pdf's you mean any type of file or specifically pdfs?

On the other hand, this configuration option is meant only for reporting proposals as it handles attachments differently than normal proposals.

**Comment by Naadjjaa** [comment]
@microstudi Seams to occur with all types of files, only fotos work. Puzzle: "All file uploads on this page are subsequently restricted to images by the module, on the grounds that direct photography with the camera is then offered on mobile phones." https://github.com/decidim-swiss/decidim.swiss/issues/93

**Comment by microstudi** [comment]
We should test if this still happens in version 27 (I think not at least in https://letterbox.dev.pokecode.net).
I'll test version 26 on Monday

**Comment by microstudi** [comment]
I confirm this exists in version 26. I've made  fix in https://github.com/openpoke/decidim-module-reporting-proposals/pull/76

**Comment by microstudi** [comment]
@Naadjjaa fix is merged, and a new version of the gem "reporting_proposals" has been published (version 0.4.2) for Decidim v0.26.
