### ISSUE TITLE
Arrow on GPS can no longer be moved

### ISSUE THREAD

**Issue by NicolaNaf** [stadtluzern/decidim-letterbox-damagereporting#57]

**Comment by NicolaNaf** [comment]
-> according to Puzzle's assessment, the fix for this bug is up to you.

I'm contacting you because of feedback from our internal people: When they report a claim and enter the address, it used to be possible to manually determine the position of the claim after an address had been entered. This is apparently no longer possible, presumably since the last update. This is very important for our internal staff, because otherwise they may have to spend a long time looking for the actual location of the damage.

https://github.com/stadtluzern/decidim-ocl/issues/282

**Comment by NicolaNaf** [comment]
@paarals can you have a look at this bug please?

**Comment by NicolaNaf** [comment]
@paarals  Can you give me an update till wednesday, 29.11. please?

**Comment by paarals** [comment]
Hi @NicolaNaf, can you point me the specific problem? 
In our staging https://letterbox.dev.pokecode.net/assemblies/luzernglaenzt/f/9/proposals

- You can move the arrow in the map
- When you move the arrow, the address is not updated because Decidim product decide that as a user you can write the specific address when you point the exacting spot in the map. Is that your problem?

**Comment by microstudi** [comment]
Hi @NicolaNaf 
This issue is due a customization in your installation that includes a javascript from the normal proposals component in the reporting proposals component. Having these two scripts together causes problems.

You have the problem in here:
![image](https://github.com/stadtluzern/decidim-letterbox-damagereporting/assets/1401520/f7c4b290-eb4f-4140-8d4d-66d9bed6fa3f)
https://github.com/stadtluzern/decidim-ocl/blob/436dfd5849256cf2596dfbfdb3d08a730621ba1c/app/providers/decidim/map/provider/dynamic_map/swisstopo.rb#L5

CC @carlobeltrame

**Comment by carlobeltrame** [comment]
@microstudi thanks for the analysis! I had no idea that you customized the map marker scripts. I have now removed the extra decidim_proposals snippet on the test server now. It must have been a leftover from some bug hunting during a Decidim upgrade.

@NicolaNaf does it work better now on test.dialogluzern.ch?

**Comment by NicolaNaf** [comment]
@microstudi Thx for the analysis.

@carlobeltrame : I can enter an address on the test platform (but this was already the case before), but the point on the map still cannot be moved manually. 
Could you please find a solution, as this function is very important for the daily tasks of our staff.

**Comment by carlobeltrame** [comment]
That means the additional script was not the real or not the only problem. @microstudi any other ideas? Since this is still a problem occurring in the damage reporting module
@NicolaNaf if you want Puzzle to debug this, please discuss this with Nicole, due to budget and resource planning constraints which she handles. Our weekly meeting on Tuesday morning would be a great place to talk.

**Comment by NicolaNaf** [comment]
@microstudi: As described by @carlobeltrame , the problem is not with the script. After consultation with Puzzle, we would be happy if you could clarify further what the problem is. 
Could you please let me know by when you expect to fix the problem? 

Please let us know when we can test the function again. After the problem has been fixed, Puzzle can add the updated code.

**Comment by microstudi** [comment]
Hi, before we discard is not the script, we should make sure that this script is not duplicated in the site. I've opened the developer tools and I still see both scripts, the proposals one and the reporting proposals. There's something that's adding both when, in the case of the reporting proposals, only the one from the module should be there.

![image](https://github.com/stadtluzern/decidim-letterbox-damagereporting/assets/1401520/b912d54c-be77-406f-a31c-9ac09eaee147)

That being said, it is possible that there are other problems but we should first discard this one. If you want we could take a deeper look at the whole application, replicate it locally but that is going to take some effort from our part.

**Comment by NicolaNaf** [comment]
@microstudi Thanks for your fast response. Can you please give me an approximate cost for analyzing and resolving the problem?

**Comment by microstudi** [comment]
probably a couple/3 of hours worth of time, which implies downloading the code, testing it locally, compiling assets and extract conclusions/make amendments if necessary (a PR).

**Comment by NicolaNaf** [comment]
@microstudi Alright. Could you  provide @carlobeltrame  and me with an update by Tuesday morning, December 12th? This will allow me to discuss the results and plan the next steps with Puzzle.

**Comment by microstudi** [comment]
sure thing, do you want to continue this conversation here or by mail?

**Comment by NicolaNaf** [comment]
To keep puzzle up to date, I would suggest continuing to communicate via this channel.

**Comment by NicolaNaf** [comment]
@microstudi Can you please give us an update?

**Comment by paarals** [comment]
> @microstudi Can you please give us an update?

will do it today, sorry

**Comment by paarals** [comment]
hi @NicolaNaf, we found the solution. it was a little bit hard from our side and it took a little bit longer: https://github.com/stadtluzern/decidim-ocl/pull/287/. please @carlobeltrame, try if that works.

**Comment by NicolaNaf** [comment]
@paarals thanks for working on the issue! sounds promising. 👍 

@carlobeltrame were you already able to have a look at this? would be great, if you can give us an update tomorrow at our meeting.

**Comment by carlobeltrame** [comment]
@NicolaNaf I deployed the fix on the test server. Could you test whether it works better now?

**Comment by NicolaNaf** [comment]
@carlobeltrame We were able to try it out on the test platform and it works again with the manual moving of the arrow for the location. The standard answers (different issue) also works again on the test platform. Since both functions are working again, we would like to make an upload on the poductive plattform. Let's discuss how we want to proceed on our next meeting in 2024.

**Comment by nicolefreypuzzle** [comment]
@NicolaNaf ist dies eigentlich mittlerweile auf PROD eingespielt? Oder müssen wir nächsten Di besprechen, wie wir damit fortfahren? 
PS. Ich kann niemanden als Assignee zuteilen.

**Comment by nicolefreypuzzle** [comment]
-------- Weitergeleitete Nachricht --------
Betreff: 	WG: [stadtluzern/decidim-letterbox-damagereporting] Arrow on GPS can no longer be moved (Issue #57)
Datum: 	Tue, 9 Jul 2024 07:53:14 +0000
Von: 	Näf Nicola <nicola.naef@stadtluzern.ch>
An: 	Nicole Frey (frey@puzzle.ch) <frey@puzzle.ch>


Liebe Nicole

Matthias konnte mir bestätigen, dass es wieder einwandfrei funktioniert.

Für unseren heutigen Austausch habe ich keine neuen Themen.

Ich wünsche dir eine schöne Woche.

Lieber Gruss
Nicola
