### ISSUE TITLE
R19. Disable rule: Start my proposal title with a capital letter

### ISSUE THREAD

**Issue by microstudi** [stadtluzern/decidim-letterbox-damagereporting#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a user, I don't want to start my proposal title with a capital letter, as is currently the case

**Mock up**
N.A.

**Does this issue could impact on users private data?**
N.A.

**Acceptance criteria**
- [x] As a user, I don't want to start with capital letters

**Technical specifications**
N.A.

**Implementation**
- [x] Initial solution: https://github.com/openpoke/decidim-letterbox-dev/pull/3
- [x] Move to https://github.com/Platoniq/decidim-module-decidim_awesome: https://github.com/Platoniq/decidim-module-decidim_awesome/pull/191

**Testing**
https://letterbox.dev.pokecode.net/processes/digital-letterbox/f/1/

**Additional context**

**Comment by microstudi** [comment]
We have a question for this too.
Should this validation be applied only to proposals? or any title (such as meetings) should not require a capital letter at the beggining?

**Comment by paarals** [comment]
we need your inputs @Naadjjaa @SandrineGis

**Comment by SandrineGis** [comment]
@paarals what kind of inputs are expected on this issue? Is there a solution we could test or do you need inputs to your question? if it is to your question: in my opinion there shouldn`t be any starts with capital letters needed in the whole proposal regarding damage reports. @Naadjjaa fyi.

**Comment by Naadjjaa** [comment]
@microstudi as we now decided to do a module I think its best only to change this inside the module.

**Comment by microstudi** [comment]
I think the best for this issue is to added as new feature for Decidim Awesome.
This way it can be scoped to only the places it is needed.

**Comment by microstudi** [comment]
PR in awesome https://github.com/Platoniq/decidim-module-decidim_awesome/pull/191

**Comment by Naadjjaa** [comment]
@paarals Could you also implement this for the description?

**Comment by paarals** [comment]
it's already done :yum: 
you can configure it here: https://letterbox.dev.pokecode.net/admin/decidim_awesome/config/proposals
![imatge](https://user-images.githubusercontent.com/40388743/194296761-8771c40f-b208-4607-a4ed-0d58e231a682.png)

**Comment by paarals** [comment]
closed by sprint 3
