### ISSUE TITLE
R18. Disable rule: at least 15 letters in my proposal title

### ISSUE THREAD

**Issue by microstudi** [stadtluzern/decidim-letterbox-damagereporting#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a user, I don't want to have to use at least 15 letters in my proposal description, as is currently the case.

**Mock up**
N.A.

**Does this issue could impact on users private data?**
N.A.

**Acceptance criteria**
- [x] As a user, I don't want to have to use 15 letters in title

**Technical specifications**
N.A.

**Implementation**
- [x] Initial solution: https://github.com/openpoke/decidim-letterbox-dev/pull/3
- [x] Move to https://github.com/Platoniq/decidim-module-decidim_awesome: https://github.com/Platoniq/decidim-module-decidim_awesome/pull/191

**Testing**
https://letterbox.dev.pokecode.net/processes/digital-letterbox/f/1/

**Additional context**

**Comment by microstudi** [comment]
Currently, we've put the minimum amount to 7 chars. Is this ok?

**Comment by paarals** [comment]
we need your inputs @Naadjjaa @SandrineGis

**Comment by microstudi** [comment]
I think the best for this issue is to added as new feature for Decidim Awesome.
This way it can be scoped to only the places it is needed.

**Comment by microstudi** [comment]
PR in awesome https://github.com/Platoniq/decidim-module-decidim_awesome/pull/191

**Comment by Naadjjaa** [comment]
![Image](https://user-images.githubusercontent.com/75797851/194282767-5111f53f-17b5-4cfc-b760-5230a4509231.png)

Can we make the yellow marked part also red?

**Comment by paarals** [comment]
closed by sprint 3
